### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by codeyso** [fasnow/idebug#1]
![image](https://github.com/fasnow/idebug/assets/49984697/9ba1c602-1879-409a-adb0-2f925d4bff04)

**Comment by fasnow** [comment]
可以代理到burp提供下截图返回的是什么数据吗

**Comment by fasnow** [comment]
> ![image](https://user-images.githubusercontent.com/49984697/244648786-9ba1c602-1879-409a-adb0-2f925d4bff04.png)

可以代理到burp提供下截图返回的是什么数据吗

**Comment by fasnow** [comment]
> ![image](https://user-images.githubusercontent.com/49984697/244648786-9ba1c602-1879-409a-adb0-2f925d4bff04.png)
现在接口被限制了，之后看能不能解决
![image](https://github.com/fasnow/idebug/assets/40886524/801cb8ef-ee6b-4234-8a4d-053f56182ae5)

**Comment by fasnow** [comment]
> > ![image](https://user-images.githubusercontent.com/49984697/244648786-9ba1c602-1879-409a-adb0-2f925d4bff04.png)
> > 现在接口被限制了，之后看能不能解决
> > ![image](https://user-images.githubusercontent.com/40886524/244685034-801cb8ef-ee6b-4234-8a4d-053f56182ae5.png)

已经更新版本
