### ISSUE TITLE
不懂问问

### ISSUE THREAD

**Issue by ChenZIDu** [fasnow/idebug#2]
想问一下，一般什么情况下能拿到这些参数

**Comment by fasnow** [comment]
什么意思呢，什么参数

**Comment by ChenZIDu** [comment]
corpid、corpsecret、access_token这类

**Comment by fasnow** [comment]
corpid、corpsecret一般得拿下配置文件才能知道，然后才能根据corpid、corpsecret获取access_token

**Comment by ChenZIDu** [comment]
配置文件位置有吗，或者相关文章有不

**Comment by fasnow** [comment]
这个一般就是服务器的配置文件，或者像nacos里放的配置文件里面，都差不多这种开头的
![image](https://github.com/fasnow/idebug/assets/40886524/c00f41bf-1fe0-423c-ad02-2d54d0973b26)

**Comment by fasnow** [comment]
> 

https://mp.weixin.qq.com/s/mptsykGJHmRC87dYqFFqMw
https://mp.weixin.qq.com/s/Ms01U9oFUe6r6xlLpGY7OA

**Comment by fasnow** [comment]
> 配置文件位置有吗，或者相关文章有不

https://mp.weixin.qq.com/s/mptsykGJHmRC87dYqFFqMw
https://mp.weixin.qq.com/s/Ms01U9oFUe6r6xlLpGY7OA
